### PR TITLE
SCuBA Section 7 & 8

### PR DESCRIPTION
**Pull request by Snozzberries**
This wraps up the Entra section. I created issue #169 for tracking of a few gaps in the implementation.

### CODE REVIEW

**Comment by merill** [comment]
Wow. Nice work @Snozzberries 

Would it be possible to make one change please?

For the roles, can we switch to using the GUIDs instead of the display name. This way it won't break functionality if the display name is ever changed.

Plus it will be good to have a short description for the switch parameter in Get-MtRole

**Comment by Snozzberries** [comment]
I think that should cover what you mentioned. Thanks for the feedback @merill.

**Comment by merill** [comment]
Another top notch addition @Snozzberries 

Amazing work.

**Comment by merill** [comment]
This has now been published to the PowerShell module. @Snozzberries quick note that I made some updates to show better message when the test passes/fails for https://github.com/maester365/maester/blob/main/powershell/public/CISA/Entra/Test-MtCisaGuestUserAccess.ps1

One was displaying the actual name of the role from the UI and the other is a deep link to the portal in the steps to make it easier to directly go to the blade.

**Comment by Snozzberries** [comment]
Thanks @merill still feeling out where to take liberties, appreciate the guidance and feedback.

**Pull request merged**
