### PR TITLE
Docs: Add 'Policy.Read.ConditionalAccess' scope

### PR DESCRIPTION
**Pull request by tbalthazar**
## Context

I'm currently setting up Maester to run in a DevOps pipeline.
I followed [the documentation](https://maester.dev/docs/monitoring/azure-devops/#grant-permissions-to-microsoft-graph) to grant permissions to the Microsoft Graph and got this error:
```
     | These Graph permissions are missing in the current connection =>
     | (Policy.Read.ConditionalAccess). Add the missing 'Application'
     | permissions in the Microsoft Entra portal and grant consent. You will
     | also need to Disconnect-Graph to refresh the permissions
```

I added the `Policy.Read.ConditionalAccess` permission and it worked.

After searching for related issues here, I saw the `Get-MtGraphScope` function had recently been updated to add this permission, but AFAICT the documentation hasn't been updated yet: https://github.com/maester365/maester/pull/178

## Proposed Changes

- Update the documentation to reflect the updated permissions required for the Microsoft Graph app.

I hope this helps!

### CODE REVIEW

**Comment by Snozzberries** [comment]
The change proposed in #190 would address this as well. As `Policy.Read.ConditionalAccess` is included in `Policy.Read.All`.

**Comment by tbalthazar** [comment]
> As Policy.Read.ConditionalAccess is included in Policy.Read.All.

@Snozzberries That's what I would have expected as well. But not explicitly adding `Policy.Read.ConditionalAccess` currently doesn't work for me. I haven't tried to add `RoleManagement.Read.All` as done in #190 though.

**Comment by Snozzberries** [comment]
Hmm, my only thought is some nuance between interactive and application permission delegations.

If you run `Connect-MgGraph -Scopes Policy.Read.All` and then `Get-MtConditionalAccessPolicy` does that throw any error in your tenant when run interactively?

If it does then can you try  `Connect-MgGraph -Scopes Policy.Read.All` and then `Get-MtConditionalAccessPolicy` to see if that resolves it.

If it doesn't throw any error then it seems related to application delegation permissions and I would need to see if I could recreate.

**Comment by tbalthazar** [comment]
Unfortunately my account doesn't have the appropriate permissions in our tenant for me to test this :/

**Comment by Snozzberries** [comment]
> Unfortunately my account doesn't have the appropriate permissions in our tenant for me to test this :/

Sounds like the role you have in your tenant may be authorized to use `Policy.Read.ConditionalAccess` but not `Policy.Read.All`. 

Is it possible to verify those delegations or try an elevated role in your tenant to confirm?

**Comment by Snozzberries** [comment]
With the following `Get-MtConditionalAccess` is able to return results.

image

I actually had the issue of until I added `Policy.Read.All` the cmdlet would return HTTP 403.

image

**Comment by tbalthazar** [comment]
> Sounds like the role you have in your tenant may be authorized to use Policy.Read.ConditionalAccess but not Policy.Read.All.

The service principal originally got those permissions granted:
image

I confirm it did not work with just `Policy.Read.All` and it started working after I added `Policy.Read.ConditionalAccess`.

**Comment by Snozzberries** [comment]
@f-bader #202, #190, and this are referencing the addition of `Policy.Read.ConditionalAccess`. It looks like this was added to scopes in #76 to support WhatIf.

I was able to confirm the `Policy.Read.ConditionalAccess` is **not** needed for `Invoke-Maester -SkipGraphConnect` today, as that bypasses the `Test-MtGraphContext` check where that scope is checked and an error is thrown if the SPN was configured with the permissions listed in the (docs)[https://maester.dev/docs/monitoring/github#grant-permissions-to-microsoft-graph].

Do you want to add switch logic for making `Policy.Read.ConditionalAccess` optional or add it to the docs as an additional required permission?

**Comment by f-bader** [comment]
I guess I will do both. 
Add a check / switch in the code like the mail permission
Add it as optional requirement in the docs

Can do the code and docs changes mid next week

**Comment by merill** [comment]
This is going to be needed by the WhatIf API as an explicit permission (it might not be included in the Policy.Read.All for some time - or ever...). Given that whatif is one of the main use cases and it will be used in future tests it will be better to consent for this up-front.

So I'm going to accept this PR and merge it in.

Thanks a lot for raising this and the discussion folks. Much appreciated.

**Pull request merged**
