### PR TITLE
Automatically install Pester if needed unless using -SkipPesterCheck

### PR DESCRIPTION
**Pull request by SamErde**
Addresses #255 and adds enhancement by adding `-Prerequisites` parameter to `Install-MaesterTests`. Checks required modules and installs them if the minimum required version is not already installed.

### CODE REVIEW

**Comment by merill** [comment]
Thanks for the PR @SamErde.

A small catch.

The Maester.psd1 file declares Pester as a required module with the specific version.

This means `Install-Module Maester` itself will fail if Pester doesn't get updated to 5.5.0. As a result the user who hits this issue will never get a chance to run the cmdlet/param you defined.

My thinking was to 
- Update the RequiredModule in Pester to not include a specific version. This way MacOS and other environments will install the latest version and Windows will skip trying to auto update and failing
- Make Install-MaesterTests **automatically** check for Pester 5.5.0 and install+import if it's not there.
- Add a -SkipPesterCheck parameter to opt out of the Pester check (instead of -Prerequisite as an opt-in)

https://github.com/maester365/maester/blob/aa79b04cbe012bfc1488eaae30848bdfc251749b/powershell/Maester.psd1#L54

Thoughts?

**Comment by SamErde** [comment]
Yes, that makes perfect sense. That flow will reduce friction for people who are just getting started. I can restructure this PR to reflect that concept.

**Comment by SamErde** [comment]
Ready for review, @merill. Is `Import-Module 'Pester'` needed? I may have missed that, but didn't see it being used previously.

**Comment by SamErde** [comment]
This build passes, but I want to look back at the previous [build validation step](https://github.com/maester365/maester/actions/runs/9636640609/job/26574838743#step:6:16) that failed when I left Pester listed as a required module but removed the version requirement. That change failed (ironically) a Pester test of the module definition file with:

```PowerShell
Error: "The 'ModuleVersion', 'MaximumVersion' and 'RequiredVersion' members do not exist in the hashtable that describes this module. One of these three members must exist, and be assigned a version number in the format 'n.n.n.n'."
```

What’s the best way to skip this specific test so we can leave it listed as a RequiredModule with no version specified?

Alternatively, we could set the minimum version here to be 3.4.0, and then re-check with Install-MaesterTests, but that also has downsides.

**Comment by SamErde** [comment]
@merill, I have done some more testing and have two options that pass Test-ModuleManifest.

- `@{ModuleName = 'Pester'; GUID = 'a699dea5-2c73-4616-a270-1f7abb777e71'; ModuleVersion = '0.0.0'; }`
- `@{ModuleName = 'Pester'; GUID = 'a699dea5-2c73-4616-a270-1f7abb777e71'; ModuleVersion = '3.4.0'; }`

The first passes manifest checks and effectively accepts any version of Pester. This allows `Install-MaesterTests` to install or update it, if necessary. 

The second also passes and looks for the version we expect to find installed out of the box in Windows.

Given the cross-platform use of Maester, do you have a preference for what goes here instead of my last commit that removed the module requirement (I didn't like that).

**Comment by merill** [comment]
Awesome. Thanks for this. I was testing the previous PR and was even testing some workarounds that involved having two .psd1 files with the first one loading the second .psd1 but it was too hacky and not reliable.

I like what you are doing here. I think it doesn't make a difference between the two options. Let's add a comment to note why we set to that version number.

**Comment by SamErde** [comment]
Glad you tested the dual PSD1 approach. I saw one blog post about doing that and it seemed very interesting, but also short on details.

Version "0.0.0" feels more OS agnostic and less misleading than declaring "3.4.0" as the required version. I don't want to trigger anyone on the "it's not actually a version" principle, but it's the direction I lean towards.

**Comment by SamErde** [comment]
Ready to roll. Thanks for the feedback!

**Review by merill — APPROVED** [review]
Nice! Thanks @SamErde !!

**Pull request merged**
