### PR TITLE
Update Test-MtEidscaPR05.ps1

### LINKED ISSUE #459: Test-MtEidscaPR05 fails because $testResult is set to type System.String
### Reproduce error
Test [Test-MtEidscaPR05.ps1](https://github.com/maester365/maester/blob/main/powershell/internal/eidsca/Test-MtEidscaPR05.ps1) fails because $tenantValue is set to type System:String `[string]$tenantValue` which results in the a wrong test result of the `-ge` [Comparison Operator](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_comparison_operators?view=powershell-7.4#-gt--ge--lt-and--le).

The description states:
> The minimum length in seconds of each lockout. If an account locks repeatedly, this duration increases.
> 
> Queries settings
> and returns the result of
> graph/settings.values | where-object name -eq 'LockoutDurationInSeconds' | select-object -expand value -ge '60'

[lines 25 to 28](https://github.com/maester365/maester/blob/061f1487cb65d994ef1ca3e6ead5ee0877c289f1/powershell/internal/eidsca/Test-MtEidscaPR05.ps1#L25-L28)
```powershell
PS C:\Users> $result = Invoke-MtGraphRequest -RelativeUri "settings" -ApiVersion beta
PS C:\Users> [string]$tenantValue = $result.values | where-object name -eq 'LockoutDurationInSeconds' | select-object -expand value
PS C:\Users> $tenantValue
120
PS C:\Users> $testResult = $tenantValue -ge '60'
PS C:\Users> $testResult
False
# 120 is greater than 60.
```

Moreover, the value not null test seems to be static/hardcoded.

[line 29](https://github.com/maester365/maester/blob/061f1487cb65d994ef1ca3e6ead5ee0877c289f1/powershell/internal/eidsca/Test-MtEidscaPR05.ps1#L29)
```powershell
$tenantValueNotSet = $null -eq $tenantValue -and '60' -notlike '*$null*'
```

### Issue resolution
```powershell
PS C:\Users> $testResult = [int]$tenantValue -ge [int]'60'
True
```

```powershell
$tenantValueNotSet = $null -eq $tenantValue -and $tenantValue -notlike '*$null*'
```

### PR DESCRIPTION
**Pull request by m-hanisch**
The value not null test seems to be static/hardcoded.
fixes #459 
[line 29](https://github.com/maester365/maester/blob/061f1487cb65d994ef1ca3e6ead5ee0877c289f1/powershell/internal/eidsca/Test-MtEidscaPR05.ps1#L29)

### CODE REVIEW

**Comment by merill** [comment]
I just realized these will get overwritten when EIDSCA generation happens see https://maester.dev/docs/contributing#updating-eidsca-tests-and-documentation

Tagging @Cloud-Architekt

**Comment by merill** [comment]
@Cloud-Architekt is this issue resolved in the last PR you submitted? If so, can I close this one? tx.

**Comment by m-hanisch** [comment]
@merill 
not yet. the `-ge` comparison operator presumes an integer value instead of the string value
See #459

**Comment by merill** [comment]
Tx for testing and confirming.  Yes please close this PR.

**Pull request closed without merging**
