### PR TITLE
A first pass at CISA docs

### PR DESCRIPTION
**Pull request by Snozzberries**
This will give at least a reference of cmdlet to CISA control and let us build on in the future.

The init.ps1 file was just my short hand to create the mapping quickly, we can remove that file if it interferes with docusaurus. 

Ref #198

### CODE REVIEW

**Comment by merill** [comment]
Nice work on the docs Michael. Thanks! 

Yes, we might need to move the init.ps1 from the docs folder. 

The ideal place to put this would be in the /build folder. I propose making a /build/cisa folder like we have for /build/eidsca 

For the sidebar label we can drop the **CISA** since it will be in the category node before it.

Merill 2024-06-01 at 20 34 00@2x

We will also need to add this to sidebars.js to create the left hand node.

```
        {
          type: "category",
          label: "🦅 CISA",
          link: {type: 'doc', id: 'tests/cisa/overview'},
          collapsed: true,
          collapsible: true,
          items: [{ type: "autogenerated", dirName: "tests/cisa" }],
        },
```

**Review by merill — CHANGES_REQUESTED** [review]
Nice work on the docs Michael. Thanks! 

Yes, we might need to move the init.ps1 from the docs folder. 

The ideal place to put this would be in the /build folder. I propose making a /build/cisa folder like we have for /build/eidsca 

For the sidebar label we can drop the **CISA** since it will be in the category node before it.

Merill 2024-06-01 at 20 34 00@2x

We will also need to add this to sidebars.js to create the left hand node.

```
        {
          type: "category",
          label: "🦅 CISA",
          link: {type: 'doc', id: 'tests/cisa/overview'},
          collapsed: true,
          collapsible: true,
          items: [{ type: "autogenerated", dirName: "tests/cisa" }],
        },
```

**Comment by Snozzberries** [comment]
Awesome, thanks for the feedback @merill I added a commit.

**Review by merill — APPROVED** [review]
Perfect. Thanks @Snozzberries !

**Pull request merged**
