### PR TITLE
Update azure-automation.md

### PR DESCRIPTION
**Pull request by BurgerhoutJ**
Added line 108 Update-MaesterTests to get the latest tests

### CODE REVIEW

**Comment by merill** [comment]
@BurgerhoutJ have you run into an issue with stale tests? The Install-MaesterTest calls the same function as Update-Maester the only difference is the check for existing folder.

So adding this extra command is not going to make any new changes.

**Comment by BurgerhoutJ** [comment]
Strange. When I added the update-maestertests, after the run I had 240+ tests instead of the 135 the first few times. 

I will check it again with and without the added command.

**Comment by merill** [comment]
Were you able to repro the issue @BurgerhoutJ ?

**Comment by BurgerhoutJ** [comment]
Sorry. Didn't have the time this week to repro.

You can close this pull request.

**Pull request closed without merging**
